### ISSUE TITLE
Extension host crashes after last VS-Code update upon compiling process

### ISSUE THREAD

**Issue by gmbhneo** [refgd/easy-complie#35]
Since the last update has been installed today, my code compiler does not work and shows the following errors:

`c:\Users\XXXXX\.vscode\extensions\refgd.easy-compile-1.2.1\out\node_modules\sass.js\dist\sass.sync.js:62
var Module=typeof Module!=="undefined"?Module:{};var moduleOverrides={};var key;for(key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var arguments_=[];var thisProgram="./this.program";var quit_=function(status,toThrow){throw toThrow};var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_HAS_NODE=false;var ENVIRONMENT_IS_SHELL=false;ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_HAS_NODE=typeof process==="object"&&typeof process.versions==="object"&&typeof process.versions.node==="string";ENVIRONMENT_IS_NODE=ENVIRONMENT_HAS_NODE&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;var scriptDirectory="";function locateFile(path){if(Module["locateFile"]){return Module["locateFile"](
abort([object Object]). Build with -s ASSERTIONS=1 for more info.

xtension host terminated unexpectedly. Code:  7  Signal:  null
_onExtensionHostCrashed @ abstractExtensionService.ts:166

(node:12924) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

  ERR Illegal value for `line`: Error: Illegal value for `line`
	at d._lineAt (c:\Users\XXXXX\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:465:884)
	at Object.lineAt (c:\Users\XXXXX\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:464:823)
	at r._lineLength (c:\Users\XXXXX\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\emmet\dist\extension.js:1:12829)
	at r.backUp (c:\Users\XXXXX\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\emmet\dist\extension.js:1:12432)
	at Object.t.parsePartialStylesheet (c:\Users\XXXXX\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\emmet\dist\extension.js:1:6453)
	at t.DefaultCompletionItemProvider.provideCompletionItemsInternal (c:\Users\XXXXX\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\emmet\dist\extension.js:1:54169)
	at t.DefaultCompletionItemProvider.provideCompletionItems (c:\Users\XXXXX\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\emmet\dist\extension.js:1:51961)
	at c:\Users\XXXXX\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:678:709
	at c:\Users\XXXXX\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:51:761
	at new Promise (<anonymous>)
	at Object.t.asPromise (c:\Users\XXXXX\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:51:733)
	at U.provideCompletionItems (c:\Users\XXXXX\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:678:680)
	at c:\Users\XXXXX\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:695:455
	at K._withAdapter (c:\Users\XXXXX\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:686:499)
	at K.$provideCompletionItems (c:\Users\XXXXX\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:695:433)
	at m._doInvokeHandler (c:\Users\XXXXX\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:801:683)
	at m._invokeHandler (c:\Users\XXXXX\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:801:375)
	at m._receiveRequest (c:\Users\XXXXX\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:799:953)
	at m._receiveOneMessage (c:\Users\XXXXX\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:798:832)
	at c:\Users\XXXXX\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:797:34
	at l.fire (c:\Users\XXXXX\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:45:801)
	at v.fire (c:\Users\XXXXX\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:235:849)
	at c:\Users\XXXXX\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:975:744
	at l.fire (c:\Users\XXXXX\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:45:801)
	at v.fire (c:\Users\XXXXX\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:235:849)
	at t.PersistentProtocol._receiveMessage (c:\Users\XXXXX\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:240:276)
	at c:\Users\XXXXX\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:237:357
	at l.fire (c:\Users\XXXXX\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:45:801)
	at p.acceptChunk (c:\Users\XXXXX\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:233:393)
	at c:\Users\XXXXX\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:232:753
	at Socket.t (c:\Users\XXXXX\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:241:826)
	at Socket.emit (events.js:203:13)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:276:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)`

**Comment by samuelpatro** [comment]
Same issue, its there a way to temporary fix it?

**Comment by YPetremann** [comment]
Same here

**Comment by ordigital** [comment]
Same here.
